# Generated by Django 4.1.3 on 2022-12-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('player_rank', models.CharField(max_length=30)),
                ('main_agents', models.CharField(choices=[('NONE', ''), ('BRIMSTONE', 'Brimstone'), ('PHEONIX', 'Pheonix'), ('SAGE', 'Sage'), ('SOVA', 'Sova'), ('VIPER', 'Viper'), ('CYPHER', 'Cypher'), ('Reyna', 'Reyna'), ('KILLJOY', 'Killjoy'), ('BREACH', 'Breach'), ('OMEN', 'Omen'), ('JETT', 'Jett'), ('RAZE', 'Raze'), ('SKYE', 'Skye'), ('YORU', 'Yoru'), ('ASTRA', 'Astra'), ('KAYO', 'Kayo'), ('CHAMBER', 'Chamber'), ('NEON', 'Neon'), ('FADE', 'Fade'), ('HARBOR', 'Harbor')], default='NONE', max_length=300)),
                ('players_signedup', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('player_rank', models.CharField(max_length=30)),
            ],
        ),
    ]
