# Generated by Django 4.1.3 on 2022-12-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valorant', '0003_alter_duo_player_rank_alter_player_player_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duo',
            name='main_agents',
            field=models.CharField(choices=[('NONE', 'No main'), ('BRIMSTONE', 'Brimstone'), ('PHEONIX', 'Pheonix'), ('SAGE', 'Sage'), ('SOVA', 'Sova'), ('VIPER', 'Viper'), ('CYPHER', 'Cypher'), ('Reyna', 'Reyna'), ('KILLJOY', 'Killjoy'), ('BREACH', 'Breach'), ('OMEN', 'Omen'), ('JETT', 'Jett'), ('RAZE', 'Raze'), ('SKYE', 'Skye'), ('YORU', 'Yoru'), ('ASTRA', 'Astra'), ('KAYO', 'Kayo'), ('CHAMBER', 'Chamber'), ('NEON', 'Neon'), ('FADE', 'Fade'), ('HARBOR', 'Harbor')], default='NONE', max_length=300),
        ),
    ]
