# Generated by Django 4.1.3 on 2022-12-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valorant', '0005_remove_duo_players_signedup_alter_duo_main_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duo',
            name='players_signedup',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
