# Generated by Django 4.1.3 on 2022-12-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valorant', '0006_duo_players_signedup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duo',
            name='main_agents',
            field=models.CharField(choices=[('No main', 'NONE'), ('Brimstone', 'Brimstone'), ('Pheonix', 'Pheonix'), ('Sage', 'Sage'), ('Sova', 'Sova'), ('Viper', 'Viper'), ('Cypher', 'Cypher'), ('Reyna', 'Reyna'), ('Killjoy', 'Killjoy'), ('Breach', 'Breach'), ('Omen', 'Omen'), ('Jett', 'Jett'), ('Raze', 'Raze'), ('&#x27;Skye&#x27;', 'Skye'), ('Yoru', 'Yoru'), ('Astra', 'Astra'), ('Kayo', 'Kayo'), ('Chamber', 'Chamber'), ('Neon', 'Neon'), ('Fade', 'Fade'), ('Harbor', 'Harbor')], default='NONE', max_length=300),
        ),
    ]
