# Generated by Django 4.1.3 on 2022-12-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valorant', '0008_alter_duo_main_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duo',
            name='main_agents',
            field=models.CharField(max_length=300),
        ),
    ]
